export const DOCUMENTS_DATA = [{
        id: 1,
        name: 'Đại số 10',
        image: 'https://toanmath.com/wp-content/uploads/2016/12/sach-giao-khoa-dai-so-10-co-ban.png',
        topic: 'Học tập',
        type: 'Sách giáo khoa',
        num: '12',
        author: 'Duy',
        publisher: 'NXB hoa hồng',
        publishDate: '2002',
        cm: '29cm',
        pageNumber: '929',
        location: 'H7w5',
        course: 'Toán',
        episodeTitle: 'Toán phổ thông',
        department: "Khoa học đại cương",
        episodeNumber: '1',
        language: 'Tiếng việt',
        illustration: '',
        price: '90000',
        tags: 'toán',
        isbn: '927126'
    },
    {
        id: 2,
        name: 'Đại vương ơi có biến',
        image: 'http://img.anime14.net/2015/04/820155705_606651055_574_574.jpg',
        topic: 'Truyện',
        type: 'Truyện trẻ em',
        num: '2',
        author: 'Cảnh',
        publisher: 'NXB hoa sen',
        publishDate: '2022',
        cm: '29cm',
        pageNumber: '29',
        location: 'H7w5s',
        course: '',
        department: '',
        episodeTitle: '',
        episodeNumber: '',
        language: 'Tiếng việt',
        illustration: 'Thế rồi 7 quả bầu lần lượt rơi xuống đất và vỡ thành 7 bé trai, mỗi bé trai có một năng lực khác nhau. Liệu anh em hồ lô có cứu được ông nội và tiêu diệt hai ...',
        price: '83000',
        tags: 'Hồ lô',
        isbn: '92172813'
    }, {
        id: 3,
        name: 'Đường kách mệnh',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Duongkachmenh.jpg/1200px-Duongkachmenh.jpg',
        topic: 'Lịch sử',
        type: 'Sách lịch sử',
        num: '412',
        author: 'Hồ Long',
        publisher: 'NXB rồng nước',
        publishDate: '1982',
        cm: '99cm',
        pageNumber: '929',
        location: 'H7w53as',
        course: 'Lịch sử',
        department: 'Khoa học đại cương',
        episodeTitle: '',
        episodeNumber: '',
        language: 'Tiếng việt',
        illustration: 'Đường Kách mệnh (hay Đường cách mệnh, tên cuốn sách trên bản gốc được viết là "Dường Kách mệnh") là tác phẩm ghi lại những bài giảng của Nguyễn Ái Quốc cho ...        ',
        price: '123000',
        tags: 'HCM',
        isbn: '92712326'
    }, {
        id: 4,
        name: 'Đại số tuyến tính',
        image: 'https://salt.tikicdn.com/ts/product/53/0b/0e/222c54554897fa471f8a178e85862f6b.jpg',
        topic: 'Học tập',
        type: 'Sách giáo khoa',
        num: '0',
        author: 'Khoa',
        publisher: 'NXB Khoa học',
        publishDate: '20902',
        cm: '29cm',
        pageNumber: '929',
        location: 'H7hw5',
        course: 'Toán',
        department: 'khoa hoc đại cương',
        episodeTitle: 'Toán cao cấp',
        episodeNumber: '9',
        language: 'Tiếng việt',
        illustration: '',
        price: '90000',
        tags: 'toán',
        isbn: '9278126'
    }
]